# frozen_string_literal: true

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'coverage/**/*'
    - 'bin/*'

# Layout cops
Layout/LineLength:
  Max: 120
  AllowedPatterns: ['(\A|\s)#']

# Style cops
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Style/OpenStructUse:
  Enabled: false

# Naming cops
Naming/PredicateMethod:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 2

# Metrics cops
Metrics/MethodLength:
  Max: 20
  CountAsOne: ['array', 'heredoc']
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Max: 30
  CountAsOne: ['array', 'heredoc']
  Exclude:
    - 'spec/**/*'
    - 'Rakefile'

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'spec/**/*'

Metrics/PerceivedComplexity:
  Max: 8
  Exclude:
    - 'spec/**/*'

Metrics/ParameterLists:
  Max: 5
  Exclude:
    - 'spec/**/*'

# RSpec specific cops
require: rubocop-rspec

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'
    - 'spec/*_resilience_spec.rb'

RSpec/PredicateMatcher:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 6

RSpec/MessageSpies:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/IdenticalEqualityAssertion:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

# Lint cops
Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

# Capybara cops
Capybara/RSpec/PredicateMatcher:
  Enabled: false
