# frozen_string_literal: true

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'coverage/**/*'
    - 'bin/*'

# Layout cops
Layout/LineLength:
  Max: 120
  AllowedPatterns: ['(\A|\s)#']

# Style cops
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

# Metrics cops
Metrics/MethodLength:
  Max: 20
  CountAsOne: ['array', 'heredoc']
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Max: 30
  CountAsOne: ['array', 'heredoc']
  Exclude:
    - 'spec/**/*'
    - 'Rakefile'

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'spec/**/*'

# RSpec specific cops
require: rubocop-rspec

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'
    - 'spec/*_resilience_spec.rb'
