name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        ruby-version: ['3.0', '3.1', '3.2']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    
    - name: Run linting
      run: bundle exec rubocop
    
    - name: Run tests
      run: bundle exec rspec
    
    - name: Upload coverage to Codecov
      if: matrix.ruby-version == '3.2'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/coverage.xml
        fail_ci_if_error: true

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t robot_challenge .
    
    - name: Test Docker image
      run: |
        echo "PLACE 0,0,NORTH" | docker run -i robot_challenge
        echo "MOVE" | docker run -i robot_challenge
        echo "REPORT" | docker run -i robot_challenge
